### ISSUE TITLE
make html error !!!

### ISSUE THREAD

**Issue by statkclee** [aroberge/reeborg-docs#3]
When I make html under the reeborg, there was no problem, but under the reeborg-docs, I've got the following error. Would you suggest any ideas?
# 잠시 멈춰서 생각하기

/home/vagrant/reeborg-docs/src/ko/variables/world.rst:40: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/vagrant/reeborg-docs/src/ko/variables/world.rst:47: ERROR: Unexpected indentation.
/home/vagrant/reeborg-docs/src/ko/variables/world.rst:55: ERROR: Unexpected indentation.
/home/vagrant/reeborg-docs/src/ko/variables/world.rst:58: ERROR: Unexpected indentation.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  5%] basics/else
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/inlinesyntaxhighlight.py", line 43, in html_visit_literal
    env = self.settings.env
AttributeError: Values instance has no attribute 'env'
The full traceback has been saved in /tmp/sphinx-err-MXWkx8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
make: **\* [html] Error 1

**Comment by aroberge** [comment]
Yes, sorry about that.  I included an additional option for sphinx (inlinesyntaxhighlight.py) which, if I remember correctly, I had to "fix" to solve a bug.    Assuming you have it installed, it should be located in your Python distribution under

Lib/site-packages/sphinxcontrib/inlinesyntaxhighlight.py

Line 43 should be replaced by

```
env = self.builder.env
```

I will try to see if I can find a way to include the correct file in reeborg-docs and change conf.py so that it automatically loads it.

**Comment by aroberge** [comment]
I have updated the repository to include the modified sphinx extension and set the path inside conf.py so that it can find it.  I have also included some other python files which are used (currently only in the French version of the docs, but soon in the other two versions) to automatically document the available functions.

This should get rid of the error you encountered.
