### ISSUE TITLE
Face North world is needed.

### ISSUE THREAD

**Issue by statkclee** [aroberge/reeborg-docs#4]
I am searching for "Face North" world.

I tried as follows;

World("http://reeborg.ca/worlds/face_north.json", "Face north")

but, I could not find any world.

Variable ---> 9. Return,

Programming time!
Run the following program to select a simple world that has Reeborg start in an arbitrary orientation:

World("/src/worlds/face_north.json", "Face north")
Then, write a short program that will ensure that Reeborg will turn left until he faces north, no matter what his starting orientation is.

**Comment by aroberge** [comment]
Simply having

World("/src/worlds/face_north.json", "Face north") 

should have worked.  Alternatively,

World("http://reeborg.ca/src/worlds/face_north.json", "Face north")

should have worked as well (notice the extra "src").   However, I just made a copy under "worlds/" instead of "src/worlds" so that either

World("http://reeborg.ca/worlds/face_north.json", "Face north")

like you had before, or

World("/worlds/face_north.json", "Face north")

should work when using Reeborg's world on my site.   The first version like you had (full url) is probably better to have in the tutorial.
